// src/components/_pages/home/experience.tsx
import { useSelector } from 'react-redux'
import { useFormat } from '@/libs/moment'

export function ExperienceComponent() {
  // __STATE <React.Hooks>
  const store = useSelector((state) => state['APP.DATA']['experience'])

  // __FUNCTION
  const getter = (input) => input.orderBy('order')
  const getDate = ({ from, to }) => {
    let _from = useFormat(from.toDate())
    let _to = useFormat(to.toDate())
    return `${_from} - ${_to}`
  }

  // __RENDER
  return (
    <div className='ui--index-experience'>
      <div className='ui--context'>
        <div className='ui--context-column col-1'>
          <h3 className='context-title-h3'>working with</h3>
          <h1 className='context-title-h1'>experiences</h1>
          <p className='context-desc'>
            It doesn't matter how great your product or service is if your copy does not captivate your audience.
          </p>
        </div>

        <div className='ui--context-column col-2'>
          <ul className='content'>
            {getter(store).map((item, index) => (
              <li className='item' key={index}>
                <svg
                  className='icon bi bi-calendar-week'
                  viewBox='0 0 16 16'
                  fill='currentColor'
                  xmlns='http://www.w3.org/2000/svg'
                >
                  <path
                    fillRule='evenodd'
                    d='M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z'
                  />
                  <path
                    fillRule='evenodd'
                    d='M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z'
                  />
                </svg>

                <div className='title'>
                  <h6 className='title-h6'>{getDate(item.time)}</h6>
                  <h3 className='title-h3'>{item.label}</h3>
                </div>

                <div className='desc'>{item.description}</div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  )
}

// src/pages/Index/Components/Experience.vue
<template>
  <div class="ui--experience">
    <div class="container">

      <div class="grid-content">
        <div class="grid-column x1">
          <h4 class="ui--info-h4">working with</h4>
          <h2 class="ui--info-h2">experiences</h2>
          <p class="ui--info-desc">
            It doesn't matter how great your product or service is if your copy does not captivate your audience.
          </p>
        </div>

        <div class="grid-column x2">
          <div class="ui--experience-list" v-for="(elm, idx) in store" :key="idx">
            <svg class="icon bi bi-calendar-week" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
              <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm-5 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
            </svg>

            <div class="title">
              <p>{{ getDate(elm.time) }}</p>
              <h4 v-text="elm.label"></h4>
            </div>

            <div class="desc" v-text="elm.description"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Vue } from 'vue-class-component'
import { dateTime } from '@/utils'

export default class ExperienceContainer extends Vue {
  [propName: string]: any

  // __METHODS
  private getDate (input: any): string {
    const from: string = dateTime(input.from.toDate())
    const to: string = dateTime(input.to.toDate())
    return `${from} - ${to}`
  }

  // __COMPUTED
  private get store (): any[] {
    const results: any = this.$store.getters['APP.DATA/experience']
    return results.orderBy('order')
  }
}
</script>
