// src/pages/Index/Components/Skill.vue
<template>
  <div class="ui--skill">
    <div class="container">

      <div class="grid-content">
        <div class="grid-column x1">
          <h4 class="ui--info-h4">creative works</h4>
          <h2 class="ui--info-h2">skills</h2>
          <p class="ui--info-desc">
            It doesn't matter how great your product or service is if your copy does not captivate your audience.
          </p>
        </div>

        <div class="grid-column x2">
          <div class="ui--skill-list" v-for="(elm, idx) in store.orderBy('order')" :key="idx">
            <span class="label" v-text="elm.label"></span>
            <span class="value" v-text="elm.value"></span>
          </div>
        </div>
      </div>

    </div>
  </div>
</template>

<script lang="ts">
import { Vue } from 'vue-class-component'

export default class SkillContainer extends Vue {
  [propName: string]: any

  // __COMPUTED
  private get store (): any[] {
    const results: any = this.$store.getters['APP.DATA/skills']
    return results.orderBy('order')
  }
}
</script>

// src/components/_pages/home/skill.tsx
import { useSelector } from 'react-redux'

export function SkillComponent() {
  // __STATE <React.Hooks>
  const store = useSelector((state) => state['APP.DATA']['skills'])

  // __FUNCTION
  const getter = (input) => input.orderBy('order')

  // __RENDER
  return (
    <div className='ui--index-skill'>
      <div className='ui--context rtl'>
        <div className='ui--context-column col-1'>
          <h3 className='context-title-h3'>creative works</h3>
          <h1 className='context-title-h1'>skills</h1>
          <p className='context-desc'>
            It doesn't matter how great your product or service is if your copy does not captivate your audience.
          </p>
        </div>

        <div className='ui--context-column col-2'>
          <ul className='content'>
            {getter(store).map((item, index) => (
              <li className='item' key={index}>
                <div className='label'>{item.label}</div>
                <div className='desc'>description</div>
                <div className='value'>{item.value}%</div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  )
}
